# Generated by Django 5.2 on 2025-05-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformticket',
            name='number_of_people',
        ),
        migrations.RemoveField(
            model_name='platformticket',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='platformticket',
            name='ticket_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
