# Generated by Django 5.2 on 2025-05-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_platformticket_number_of_people_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expressticket',
            old_name='to_station',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='expressticket',
            name='from_station',
        ),
        migrations.AddField(
            model_name='expressticket',
            name='source',
            field=models.CharField(default='Demo src', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expressticket',
            name='train_name',
            field=models.CharField(default='Demo Train', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expressticket',
            name='travel_class',
            field=models.CharField(default='Demo class', max_length=64),
            preserve_default=False,
        ),
    ]
