# Generated by Django 5.2 on 2025-05-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_to_station_expressticket_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localticket',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='localticket',
            name='line',
        ),
        migrations.AddField(
            model_name='localticket',
            name='line_direction',
            field=models.CharField(default='line and direction', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localticket',
            name='ticket_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
